### ISSUE TITLE
`tpn` task creates bogus end-nodes

### ISSUE THREAD

**Issue by pmdoll** [dollabs/pamela#103]
See issue #101 and use first.pamela for details. I am blocked on this issue

**Comment by tmarble** [comment]
@pmdoll could you please elaborate?

**Comment by pmdoll** [comment]
For node-102, end-node is node-99 but there is no object for node-99.

```
"node-102": {
  "tpn-type": "state",
  "uid": "node-102",
  "constraints": [],
  "activities": [
    "act-101"
  ],
  "incidence-set": [
    "act-92"
  ],
  "end-node": "node-99"

```

**Comment by tmarble** [comment]
Was able to reproduce with

```
tmarble@cerise 526 :) ./bin/pamela -i test/pamela/first.pamela -o first -f edn -t "(main-htn.tpn.start)" htn
tmarble@cerise 530 :) ../planviz/bin/planviz -i first.tpn.edn=first.htn.edn
17-May-02 12:29:45.547 cerise WARN [planviz.server:0] - 
PLANVIZ server ready
```

NOTE: the TPN renders correctly in PLANVIZ. The symptom appears to be that certain state nodes have an invalid :end-node (which is likely due to a bug in `remove-superfluous-null-activities`.
