### ISSUE TITLE
state nodes and their :end-nodes

### ISSUE THREAD

**Issue by pmdoll** [dollabs/pamela#105]
Prior to IR days, generated TPN `state` nodes had :sequence-end node pointing to the end node of the sequence. 

Current TPN `state` nodes have :end-node pointing to the end-node of the activity instead of the end-node of the sequence. This is the case for TPNs generated by both `htn and tpn` task.

Also, the :end-node is not always present.

`from first.tpn.json`
```
  "node-28": {
    "tpn-type": "state",
    "uid": "node-28",
    "constraints": [],
    "activities": [
      "na-34"
    ],
    "incidence-set": [
      "act-46"
    ]
  },
```

**Comment by tmarble** [comment]
@pmdoll so are you requesting
1. state :end-nodes point to the end of the sequence (if apropos, else end of activity), -or-
2. state nodes that begin a sequence *should also* have a :sequence-end that points to the end of the sequence?

**Comment by pmdoll** [comment]
I am requesting that only `state` nodes that are part of a sequence should have end-node attribute set. Not otherwise.

**Comment by pmdoll** [comment]
For state nodes, current planner code not depend on end-node anymore.

**Comment by dcerys** [comment]
Need to establish clear semantics for what the :end-node of a state node means.
The specifics of :end-node (for a state node) are currently ill-defined, and the use of it currently doesn’t depend on any specific value (e.g., the planner and dispatcher currently don’t care).
