### ISSUE TITLE
IR generation error for defpmethods with betweens, but no body

### ISSUE THREAD

**Issue by tmarble** [dollabs/pamela#128]
There is an error in the IR for files that have an empty body, but do have between statements.. the IR accidentlly ends up in the :body of the fn (instead of the :betweens). Examples include:

* test/pamela/regression/
  * between-ends.pamela
  * between-example.pamela
  * between-starts-example.pamela

**Comment by dcerys** [comment]
Sounds analogous to #122.  Likely a similar parser bug.
