### ISSUE TITLE
Is GPL compatible with our Apache license?

### ISSUE THREAD

**Issue by pmdoll** [dollabs/pamela#141]
[UnBBayes License](https://sourceforge.net/p/unbbayes/wiki/License/) text suggests it might be.

Our software distributions are open source, licensed under the GNU General Public License. Note that **_this license allows many free uses_**, but does not allow its incorporation (even in part, in translation, or in any derivative form) into any type of proprietary software which you distribute. However, we also offer commercial licensing; please contact us if you are interested.

**Comment by tmarble** [comment]
I am not a lawyer. I am not your lawyer. This is not legal advice. For matters of license interpretation seeking advice of counsel is highly recommended.

The license used for PAMELA is the standard Apache 2.0 license as approved by the Open Source Initiative (it is only "ours" in the sense that PAMELA copyright holders have chosen to use this standard license).

You may find the following links instructive:
* https://www.gnu.org/licenses/quick-guide-gplv3#new-compatible-licenses
* https://www.gnu.org/licenses/license-list.html#apache2

**Comment by pmdoll** [comment]
Thanks for links. They are informative and helpful in making an informed decision and are exactly what I was looking for.
