### ISSUE TITLE
Pamela-setup script fails

### ISSUE THREAD

**Issue by dvanelst** [dollabs/pamela#186]
I tried installing Pamela using the installation instructions. Which boils down to executing:
`curl -fsSLo pamela-setup https://raw.githubusercontent.com/dollabs/pamela/master/bin/pamela-setup && chmod +x pamela-setup && ./pamela-setup`

Java, git and the directories are all installed and created correctly. Installing boot per script did not work immediately, but I installed it from hand, works. Webkeys and webtasks seem to install OK. Plan-schema, planviz and pamela display problems. 
Errors during compilation and problems "repositoryOfflineException" trying to acces repo.clojars.org for repositories which are not only (their respective github repositories also state that these are not contained).

I attached the complete output of the script. 
[Pamela script execution - output.txt](https://github.com/dollabs/pamela/files/3213148/Pamela.script.execution.-.output.txt)

System information:
Virtual Box, Ubuntu 18.0.4, Boot 2.8.3

**Comment by pmdoll** [comment]
Which version of java is installed on your VM?

**Comment by dvanelst** [comment]
The "default-jdk" was installed. 
java --version displays:

openjdk 11.0.3 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.04.1, mixed mode, sharing)

**Comment by dvanelst** [comment]
That question solves the problem. I removed java, installed 1.8:
```
java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.19.04.2-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)
```
(Do not wonder about Ubuntu now being 19.04.2. Does not influence the problem.)

The boot issues suggest that boot does not work with the openjdk 11 that comes with Ubuntu 19.

However, boot still does not install with the pamela script. This oneliner from the boot repository did the trick:
`sudo bash -c "cd /usr/local/bin && curl -fsSLo boot https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh && chmod 755 boot"`
