### ISSUE TITLE
Missing files/errors from README.md and Documentation

### ISSUE THREAD

**Issue by ThaoPhuong1407** [dollabs/pamela#192]
- **Missing tpn-demo.tpn.edn** `./bin/pamela -i test/pamela/tpn-demo.pamela -o tpn-demo.tpn.edn tpn`

- **Missing test/pamela/choice-tpn.pamela** `pamela -i test/pamela/plant.pamela -i test/pamela/choice-tpn.pamela -f json -o choice-tpn.tpn.json tpn`

- **Possible TPN operation errors when executing:** `pamela -i test/pamela/tpn-demo.pamela tpn` or `./bin/pamela -i test/pamela/tpn-demo.pamela -o tpn-demo.tpn.edn tpn`
	1. Unable to determine tpn plant, more than one pclass takes zero args
 	2. Unable to find the default TPN method: please specify --construct-tpn pclass:field:method
 	3. Unable to create TPN: [#object[java.io.File 0x17240340 "/Users/tphuong/pamela/pamela/test/pamela/tpn-demo.pamela"]]

**Comment by dcerys** [comment]
Where is that 2nd item (Missing test/pamela/choice-tpn.pamela) described in the documentation?

**Comment by ThaoPhuong1407** [comment]
> Where is that 2nd item (Missing test/pamela/choice-tpn.pamela) described in the documentation?

It is in here (pamela/doc/TPN.md): https://github.com/dollabs/pamela/blob/master/doc/TPN.md

**Comment by dcerys** [comment]
@ThaoPhuong1407   Thanks for identifying these problems in the doc!
