### ISSUE TITLE
Broken pamela files

### ISSUE THREAD

**Issue by pmdoll** [dollabs/pamela#193]
`test/pamela/parallel.pamela` does not compile.

```
pamela -i parallel.pamela -t "(parallel-tpn.simple-parallel-tpn)" htn
20-07-29 18:44:56 Rising-Sun-2 ERROR [pamela.htn:0] - pclass constructor arity mismatch for pclass parallel-tpn expecting [plant] provided []
20-07-29 18:44:56 Rising-Sun-2 ERROR [pamela.cli:0] - 
 ERROR caught exception:
pclass constructor arity mismatch for pclass parallel-tpn expecting [plant] provided []
```

 * All pamela files should be compilable
 * All pamela files should include the command to compile them

**Comment by dcerys** [comment]
Many of the Pamela files are used only for IR generation testing, and not for HTN generation.
I'll create a test/pamela/README.md file to clarify this.
