### ISSUE TITLE
TPN Choice End nodes are missing null activities

### ISSUE THREAD

**Issue by pmdoll** [dollabs/pamela#62]
For `pamela/test/simple-choice/choice.feasible.pamela` TPN in planviz  does not render correctly. 

[TPN Choice View](https://github.com/dollabs/pamela/blob/fa48706b933f9ff4267673f95532f139659068ce/test/simple-choice/choice.feasible.png)

[TPN Parallel View looks better](https://github.com/dollabs/pamela/blob/a705ee3fc4c12e9ea857ec0ffea00e968cec0f50/test/simple-choice-parallel/parallel.feasible.png)

**Comment by pmdoll** [comment]
The box at the top of the view port is visible in both firefox and chrome when zoomed out to 70% and 100% respectively on OSX-sierra. The box is a hidden `help-menu` that appears when zoomed out.

**Comment by tmarble** [comment]
Fixed in d837438e1c8324465569c7eddf72185b98cdde67
