### ISSUE TITLE
HTN state mismatch (in Planviz) between parents and children

### ISSUE THREAD

**Issue by dcerys** [dollabs/pamela#66]
During the execution of this HTN, the top-level and 2nd-level parents are colored dark green, even though the 3rd level parent is still in-progress.  The  top-level and 2nd-level parents should remain light green until all of the children (just the one 3rd level parent in this case) is complete.

![screenshot 2017-02-17 08 39 20](https://cloud.githubusercontent.com/assets/2280962/23078730/e18d7a80-f517-11e6-9743-c07bee905d97.png)

**Comment by pmdoll** [comment]
This issue does not manifest with latest versions pamela and planviz as of today.

**Comment by dcerys** [comment]
Verified this this problem no longer occurs, using the same plan.  The fix was part of the overall HTN refactoring recently completed.
