### ISSUE TITLE
constraints not created for plant activities

### ISSUE THREAD

**Issue by pmdoll** [dollabs/pamela#67]
```
## In github/dollabs/pamela
pamela -v -v -i sequence.feasible.pamela -o sequence.feasible.cfm.tpn.json -c sequence-feasible:main:main -f json tpn
```

Generated TPN does not has any constraints.

**Comment by tmarble** [comment]
In #68 I have added some additional variants on how to represent this TPN.

The problems with `sequence.feasible.pamela` are

1. The TPN class tries to instantiate itself as a field 
2. The TPN class constructor does not provide the required plant argument
3. The `plnt` is never created
4. In this case there is a "zero-arg plant and a one-arg TPN Pamela class" such that the C:F:M argument should not be necessary.

The example `sequence2.feasible.pamela` fixes the problems above when used with the command line

`(pamela "-v" "-v" "-i" "./test/pamela/sequence2.feasible.pamela" "-o" "sequence2.feasible.cfm.tpn.json" "-f" "json" "tpn")`

_However_: the current bug still appears in this "zero-arg plant and a one-arg TPN Pamela class" approach

The example `sequence3.feasible.pamela` fixes the problems above when used with the command line

`(pamela "-v" "-v" "-i" "./test/pamela/sequence3.feasible.pamela" "-o" "sequence3.feasible.cfm.tpn.json" "-c" "demo:tpn:main" "-f" "json" "tpn")`

And it works as intended as the C:F:M are as expected. As this method of TPN generation will be deprecated in #42 I propose we write our direct TPN's in the correct C:F:M style for now.
