### ISSUE TITLE
Decide on argsmap format

### ISSUE THREAD

**Issue by tmarble** [dollabs/pamela#70]
Currently we have two slots for plant methods
* args - vector of literal values passed to the method
* argsmap - map (or JSON object) of **formal-arg** keys to **arg** values

However argsmap drops the position of the args.

If, instead, we had a vector of vectors then we would have all the data:

  argsmap: [[param0 val0] [param1 val1] ....]

for example

  argsmap: [[loc1 "e1h1"] [loc2 "e2h1"] [loc3 "e3h1"] [loc4 "e4h1"]]

In fact.. with this argsmap we really wouldn't need the :args slot
because we could derive it with: (mapv second argsmap)

The goal of this ticket is to decide which format to use for argsmap.

**Comment by pmdoll** [comment]
They are intended to be generated from pamela and never updated. It is was conscious trade-off to include the redundant data for developers implementing backends, plants etc in other languages. The idea is that if a language supports converting vectors and maps to method arguments, then invoking methods would be trivial.

args and argsmap are in place to support native plant method invocations. Any changes to these data structures will affect downstream plant implementations and I don't see any value proposition in changing their structure.

However, there may be some value to having position of the args. So, in line with Rich Hickey's talk, I am open to the idea of adding another slot that addresses the issue.

**Comment by dcerys** [comment]
Going forward, we propose to make the following INCOMPATIBLE changes:

- **:args** will remain as-is
E.g., ```["west" 30]```
- :argsmap will be **obsolete**.  Initially, it will be simply deprecated.  Soon afterwards, it will be eliminated from any generated TPN files.
- **:args-mapping** will be added, as an ordered vector of pairs.  The first element of each pair is the formal argument name.  The second element of each pair is the argument value.  
E.g., ```[["direction" "west"] ["altitude" 30]]```

I'll capture this in [doc/TPN.md](https://github.com/dollabs/pamela/blob/master/doc/TPN.md)

**Comment by dcerys** [comment]
We've agreed to adopt the :args and :args-mapping approach.
This will be implemented via Issue #43
