### ISSUE TITLE
state end-node

### ISSUE THREAD

**Issue by pmdoll** [dollabs/pamela#80]
Planviz is complaining about end-nodes.

In `pamela/test/simple-choice-parallel`
```
pamela -i parallel.feasible.pamela -t "(parallel-feasible.main)" -o parallel.feasible htn
planviz -v -v -l debug -i parallel.feasible.tpn.json -i parallel.feasible.htn.json
# snip
Reading input from: parallel.feasible.tpn.json
17-Mar-31 15:56:32.924 pablo DEBUG [planviz.server:0] - END NODE :parallel.feasible.tpn:node-20 NOT FOUND?
17-Mar-31 15:56:32.925 pablo DEBUG [planviz.server:0] - END NODE :parallel.feasible.tpn:node-5 NOT FOUND?
17-Mar-31 15:56:32.926 pablo DEBUG [planviz.server:0] - END NODE :parallel.feasible.tpn:node-14 NOT FOUND?
```

* Why is planviz complaining about these nodes?

In the generated tpn file, state nodes have an end node. Only the state nodes that represent beginning of a `actual sequence` should have end node slot. i.e (sequence (act1) (act2)) and not otherwise

**Comment by tmarble** [comment]
Note: PLANVIZ calls the plan-schema merge operation upon loading plans, thus this is really a plan-schema issue:

```
tmarble@cerise 131 :) ./bin/plan-schema -i ../pamela/test/pamela/HTN/parallel.feasible.htn.edn \
  -i ../pamela/test/pamela/HTN/parallel.feasible.tpn.edn \
  -o parallel.feasible.merge.edn merge
Reading input from: ../pamela/test/pamela/HTN/parallel.feasible.htn.edn
Reading input from: ../pamela/test/pamela/HTN/parallel.feasible.tpn.edn
DEBUG END NODE :parallel.feasible.tpn:node-58 NOT FOUND?
DEBUG END NODE :parallel.feasible.tpn:node-67 NOT FOUND?
DEBUG END NODE :parallel.feasible.tpn:node-73 NOT FOUND?
tmarble@cerise 132 :) 
```

**Comment by pmdoll** [comment]
Ok, what is the issue? What is plan-schema trying to do here during the merge operation?

**Comment by tmarble** [comment]
This is an old debugging statement that can probably go away.

**Comment by tmarble** [comment]
Closed by https://github.com/dollabs/plan-schema/commit/d6160aa23c4088c3f83d0df592dc9f2d61fe10c5

NOTE: PAMELA and PLANVIZ build.boot will need to be updated with this version of plan-schema.
