### ISSUE TITLE
Symbol/Keyword Arg Values in Method Calls

### ISSUE THREAD

**Issue by dcerys** [dollabs/pamela#81]
Argument values in method calls (i.e., argvals of plant-fn calls) that are symbols/keywords are kept as literal symbols, in contrast to other symbols (like the method name) which are parsed into context-ful structures (maps).  This is true for: the generated IR, HTN, and TPN.
It might be useful **(perhaps essential?)** to do the same as for arguments to a Pamela conditional.

E.g., 
The method invocation:

```
(generator.generate-candidate-positions :gu1.next-lat :gu1.next-lon 
   :gu2.next-lat :gu2.next-lon :gu3.next-lat :gu3.next-lon)
```
generates the following in the IR:

```
{:type :plant-fn-field,
        :method generate-candidate-positions,
        :args
        [:gu1.next-lat
         :gu1.next-lon
         :gu2.next-lat
         :gu2.next-lon
         :gu3.next-lat
         :gu3.next-lon],
        :field :generator}
```
These literals carry through from the IR to the generated HTN and TPN.  So, it's up to the user of the activities (e.g., the Dispatcher) to (re)construct the context and perform the correct dereferencing.  **The problem is that the complete context won't be available** (unless we pull the IR along all the way).  In the above example, there is no way that the field variable `:gu1` corresponds to the `ground-unit` pclass instance with the `:plant-id` of `"ground-unit1"`.  

In contrast, the conditional `(= :cannon-f.:ammunitions 0)`
is expanded into

```
{:type :equal,
 :args [{:type :field-reference-field,
         :pclass this,
         :field :cannon-f,
         :value :ammunitions}
         {:type :literal, :value 0}]}
```

Still, this assumes some context that might not be available downstream, but it's a better situation.  We would still need to be able to determine the appropriate pclass-ctor (in order to obtain the correct :plant-id and :plant-part).  Of course, expanding all method args in this manner would require changes throughout `htn.clj` and in the Dispatcher.

**Comment by tmarble** [comment]
@dcerys do you have a complete, motivating example PAMELA source file? I'm going to work on creating one (if not). My idea is to show the current vs. proposed IR as generated and ensure I understand exactly how you'd like it to be.

**Comment by tmarble** [comment]
@dcerys I have created a sample file for you to evaluate:
https://github.com/tmarble/pamela/blob/issue-81/test/pamela/issue-81.pamela

NOTE: this syntax currently *does not build*. Please advise if this is what you want.

**Comment by dcerys** [comment]
The example is sufficient to illustrate the requirement, but it raises another Pamela language issue, that I'll describe in a separate email.

**Comment by dcerys** [comment]
Before spending the time to create the complete IR for `issue-81-nocolons.pamela` (programmatically or hand-coded), let's review just the snippet of the IR that (will) corresponds to `(p2.scp p2.data1 p2.data2)`
