### ISSUE TITLE
Single-pclass Pamela file displays a spurious ERROR

### ISSUE THREAD

**Issue by dcerys** [dollabs/pamela#82]
This single-pclass Pamela file displays a spurious ERROR:
`ERROR, not currently supported plant-fn type= nil`

Using `(arg-test1.one)` as the root task

However, the generated HTN and TPN seem correct 
```
(defpclass arg-test1 []
  :methods [(defpmethod one []
              (sequence
               (two 1 2)))
            (defpmethod two [a1 a2]
              (three a1 a2))
            (defpmethod three [b1 b2])
            ])
```

**Comment by tmarble** [comment]
Tested fix with `(pamela "-i" "issue-82.pamela" "-o" "issue-82" "-t" "(arg-test1.one)" "htn")`
[issue-82.pamela.txt](https://github.com/dollabs/pamela/files/900585/issue-82.pamela.txt)
